version: '3'
services:
    web:
        build:
            context: ./web
            dockerfile: Dockerfile
        ports:
            - "9007:80"
    webapp:
        build:
            context: ./webapp
            dockerfile: Dockerfile
        ports:
            - "9006:5000"